# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_auto_20171028_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='destination',
            field=models.CharField(default='Texas', max_length=255),
            preserve_default=False,
        ),
    ]
