# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_destination_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='user',
        ),
        migrations.AddField(
            model_name='destination',
            name='users',
            field=models.ManyToManyField(related_name='destinations', to='travel.User'),
        ),
    ]
